name: OpenVPN
services:
    to:
        container_name: openvpn-as
        devices:
            - /dev/net/tun
        cap_add:
            - MKNOD
            - NET_ADMIN
        ports:
            - 943:943
            - 443:443
            - 1194:1194/udp
        volumes:
            - <path
        image: to
        command: D:\OpenVPN:/openvpn --restart=unless-stopped openvpn/openvpn-as



docker run -d --name=openvpn-as --device /dev/net/tun --cap-add=MKNOD --cap-add=NET_ADMIN -p 943:943 -p 443:443 -p 1194:1194/udp -v D:\OpenVPN:/openvpn --restart=unless-stopped openvpn/openvpn-as