apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 100Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media2-pv
spec:
  capacity:
    storage: 100Gi  # Adjust the size as needed
  accessModes:
    - ReadOnlyMany # Set to read-only
  hostPath:
    path: /path/to/media2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-fonts-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  accessModes:
    - ReadOnlyMany # Set to read-only
  hostPath:
    path: /path/to/fonts
