apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 0
      hostNetwork: true  # This is for network_mode: 'host'
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          volumeMounts:
            - name: fonts-volume
              mountPath: /usr/local/share/fonts/custom
              readOnly: true
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: jellyfin-cache-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi # Recommended size for configuration
    - metadata:
        name: jellyfin-config-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi # Recommended size for configuration
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    # Use standard HTTP and HTTPS ports since hostNetwork is enabled
    - protocol: TCP
      port: 80
      targetPort: 8096  # Port used by Jellyfin container for HTTP
    - protocol: TCP
      port: 443
      targetPort: 8920  # Port used by Jellyfin container for HTTPS
  type: NodePort  # Or NodePort, LoadBalancer depending on your cluster setup
