# This PVC is for the Jellyfin config and will be managed outside the StatefulSet.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8096
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8920
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  serviceName: "jellyfin" # StatefulSet requires a serviceName
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 0
      hostNetwork: true
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          volumeMounts:
            - name: config-volume # Mount for the static PVC
              mountPath: /config
            - name: media-volume # Mount for the static media PVC
              mountPath: /data/media
            - name: fonts-volume # Ephemeral volume
              mountPath: /usr/local/share/fonts/custom
              readOnly: true
            - name: jellyfin-cache-pvc # Mount for the cache volumeClaimTemplate
              mountPath: /cache
          ports:
            - containerPort: 8096
            - containerPort: 8920
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-qbittorrent-0
        - name: fonts-volume
          emptyDir: {}
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: jellyfin-cache-pvc # This template creates the PVC for the cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
