apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      hostNetwork: true  # This is for network_mode: 'host'
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: cache-volume
              mountPath: /cache
            - name: media-volume
              mountPath: /media
            - name: media2-volume
              mountPath: /media2
              readOnly: true
            - name: fonts-volume
              mountPath: /usr/local/share/fonts/custom
              readOnly: true
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: jellyfin-cache-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi # Recommended size for configuration
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    # Use standard HTTP and HTTPS ports since hostNetwork is enabled
    - protocol: TCP
      port: 80
      targetPort: 8096  # Port used by Jellyfin container for HTTP
    - protocol: TCP
      port: 443
      targetPort: 8920  # Port used by Jellyfin container for HTTPS
  type: NodePort  # Or NodePort, LoadBalancer depending on your cluster setup
