apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  accessModes:
    - ReadWriteOnce # or ReadWriteMany if supported by your StorageClass
  resources:
    requests:
      storage: 5Gi # Recommended size for configuration
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
spec:
  accessModes:
    - ReadWriteOnce # or ReadWriteMany if needed
  resources:
    requests:
      storage: 500Gi # Recommended size for downloads
